"""Public translation API — single entry point used by both the FastAPI
service and the CLI.

This module is intentionally thin: it composes :mod:`.translate.parser`,
:mod:`.translate.visitor`, :mod:`.translate.builder`, and
:mod:`.translate.resolver` into a single ``translate()`` call so callers
do not have to wire the pipeline themselves.

See ``.cursor/skills/sparql-to-aql/SKILL.md`` for the porting recipe
each new SPARQL construct must follow.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .translate.builder import AqlQueryBuilder
from .translate.parser import parse_sparql
from .translate.resolver import SchemaResolver
from .translate.visitor import AlgebraVisitor

_SCHEMA_WARNING_CODE_PREFIX = "W_SCHEMA_"


@dataclass
class TranslateResult:
    """Result of a SPARQL → AQL translation.

    ``warnings`` aggregates every advisory emitted during the translate —
    both the AQL builder's general advisories (e.g. truncated regex
    flags) and the :class:`SchemaResolver`'s schema-mapping advisories
    (unmapped IRI fallback, default-collection fallback).
    ``schema_warnings`` is the schema-only subset, surfaced as a
    convenience so the UI can render those advisories in their own
    panel without re-filtering. The two lists overlap deliberately: a
    schema warning appears in both ``warnings`` and ``schema_warnings``.
    """

    aql: str
    bind_vars: dict[str, Any] = field(default_factory=dict)
    warnings: list[dict[str, Any]] = field(default_factory=list)
    schema_warnings: list[dict[str, Any]] = field(default_factory=list)


def translate(
    sparql: str,
    *,
    resolver: SchemaResolver,
    params: dict[str, Any] | None = None,
    tenant_id: str | None = None,
) -> TranslateResult:
    """Translate a SPARQL 1.1 query string into AQL.

    Parameters
    ----------
    sparql:
        The SPARQL 1.1 query string. Any string accepted by
        ``rdflib.plugins.sparql.parser.parseQuery`` is accepted here.
    resolver:
        Schema resolver wrapping the OWL/Turtle ontology produced by
        ``arango-schema-mapper``. Owns URI → physical
        collection/edge/property mapping.
    params:
        Optional dict of caller-supplied bind variables (e.g. ``{"limit": 10}``).
        Reserved names (those generated by the AQL builder) are rejected at
        compose time.
    tenant_id:
        Per-request tenant identifier sourced upstream from the session's
        ``X-Tenant-Id`` header (PRD §6.5.1). Each entity whose
        :class:`~arango_sparql.translate.resolver.ResolvedClass` carries a
        ``tenant_field`` gets gated with
        ``FILTER doc.<tenant_field> == @tenant``. ``None`` is fine for
        single-tenant deployments (no class declares ``phys:tenantField``);
        a tenant-scoped class with ``tenant_id=None`` raises
        :class:`~arango_sparql.errors.CrossTenantJoinError`.

    Returns
    -------
    TranslateResult
        Generated AQL plus bind variables and any non-fatal warnings.
    """
    parsed = parse_sparql(sparql)
    builder = AqlQueryBuilder(seed_params=params or {})
    visitor = AlgebraVisitor(
        builder=builder,
        resolver=resolver,
        explicit_projection=parsed.explicit_projection,
        describe_resources=parsed.describe_resources,
        tenant_id=tenant_id,
    )
    visitor.visit(parsed.algebra)
    aql, bind_vars = builder.finalize()
    # Merge resolver advisories ahead of builder advisories so the UI
    # renders schema-mapping issues first (operator usually fixes the
    # mapping, then the AQL warnings often disappear on their own).
    combined_warnings: list[dict[str, Any]] = list(resolver.warnings) + list(builder.warnings)
    schema_warnings = [
        w for w in combined_warnings if str(w.get("code", "")).startswith(_SCHEMA_WARNING_CODE_PREFIX)
    ]
    return TranslateResult(
        aql=aql,
        bind_vars=bind_vars,
        warnings=combined_warnings,
        schema_warnings=schema_warnings,
    )
